
version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: shaun
      POSTGRES_PASSWORD: 123546
      POSTGRES_DB: localdev
    ports:
      - "5433:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: my_adminer_container
    ports:
      - "8080:8080"

  dash_app:
    build: ./dash  # Specify the path to your Dash app's Dockerfile
    container_name: my_dash_app_container
    ports:
      - "8050:8050"  # Dash runs on port 8050 by default
    volumes:
      - ./dash/app:/usr/src/app  # Mount the app directory as a volume

volumes:
  my_postgres_data:
