# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /

# Install any needed packages specified in requirements.txt
COPY ./requirements.txt ./requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt


# Make port 8050 available to the world outside this container
EXPOSE 8050

# Define environment variable for Dash to run in production (optional)
ENV DASH_ENV=development
ENV FLASK_ENV=development


# Run app.py when the container launches
WORKDIR /usr/src/app
CMD ["python","app.py","--debug"]